server.port=8080

# ===============================
# DATABASE - POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque
spring.datasource.username=bibliotheque
spring.datasource.password=bibliotheque

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Compatibilite avec la configuration Spring Security existante
spring.main.allow-circular-references=true
